// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Js_array from "rescript/lib/es6/js_array.js";
import * as Js_string from "rescript/lib/es6/js_string.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

function includeOther(r0, r1) {
  if (Caml_obj.lessequal(Caml_array.get(r0, 0), Caml_array.get(r1, 0))) {
    return Caml_obj.greaterequal(Caml_array.get(r0, 1), Caml_array.get(r1, 1));
  } else {
    return false;
  }
}

function includeAny(r0, r1) {
  if (includeOther(r0, r1)) {
    return true;
  } else {
    return includeOther(r1, r0);
  }
}

function overlap(r0, r1) {
  if (Caml_obj.greaterequal(Caml_array.get(r0, 0), Caml_array.get(r1, 0)) && Caml_obj.lessequal(Caml_array.get(r0, 0), Caml_array.get(r1, 1))) {
    return true;
  } else if (Caml_obj.greaterequal(Caml_array.get(r1, 0), Caml_array.get(r0, 0))) {
    return Caml_obj.lessequal(Caml_array.get(r1, 0), Caml_array.get(r0, 1));
  } else {
    return false;
  }
}

function toRanges(line) {
  return Js_array.map((function (range) {
                return Js_array.map(Belt_Int.fromString, Js_string.split("-", range));
              }), Js_string.split(",", line));
}

function part01(input) {
  return Js_array.filter((function (ranges) {
                if (ranges.length !== 2) {
                  return false;
                }
                var r0 = ranges[0];
                var r1 = ranges[1];
                return includeAny(r0, r1);
              }), Js_array.map(toRanges, input)).length;
}

function part02(input) {
  return Js_array.filter((function (ranges) {
                if (ranges.length !== 2) {
                  return false;
                }
                var r0 = ranges[0];
                var r1 = ranges[1];
                return overlap(r0, r1);
              }), Js_array.map(toRanges, input)).length;
}

export {
  includeOther ,
  includeAny ,
  overlap ,
  toRanges ,
  part01 ,
  part02 ,
}
/* No side effect */
