// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Day01 from "../rescript-src/Day01.bs.js";

Zora.test("all tests", (function (t) {
        t.equal(Day01.part02(undefined), 213089, "Fail");
        t.equal(Day01.part01(undefined), 72718, "Fail");
      }));

export {
  
}
/*  Not a pure module */
