// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Day01Part01 from "../rescript-src/Day01Part01.bs.js";
import * as Day01Part02 from "../rescript-src/Day01Part02.bs.js";

Zora.test("testing_works", (function (t) {
        t.equal(Day01Part01.run(undefined), 72718, "Fail");
      }));

Zora.test("testing_works", (function (t) {
        t.equal(Day01Part02.run(undefined), 213089, "Fail");
      }));

export {
  
}
/*  Not a pure module */
