[package]
name = "advent_of_code"
version = "0.0.22"
edition = "2021"


[dependencies]
tuple = "0.5.1"
itertools = "0.10.5"
regex = "1.7.0"
pathfinding = "4.1.1"
nom = "7.1.1"

[dev-dependencies]
# criterion = "0.4.0"
glassbench = "0.3"

[[bench]]
name = "my_benchmark"
harness = false
