// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_array from "rescript/lib/es6/js_array.js";

function part01(input) {
  var scoring = Js_dict.fromArray([
        [
          "A X",
          4
        ],
        [
          "A Y",
          8
        ],
        [
          "A Z",
          3
        ],
        [
          "B X",
          1
        ],
        [
          "B Y",
          5
        ],
        [
          "B Z",
          9
        ],
        [
          "C X",
          7
        ],
        [
          "C Y",
          2
        ],
        [
          "C Z",
          6
        ]
      ]);
  return Js_array.reduce((function (accu, val) {
                return accu + scoring[val] | 0;
              }), 0, input);
}

function part02(input) {
  var scoring = Js_dict.fromArray([
        [
          "A X",
          3
        ],
        [
          "A Y",
          4
        ],
        [
          "A Z",
          8
        ],
        [
          "B X",
          1
        ],
        [
          "B Y",
          5
        ],
        [
          "B Z",
          9
        ],
        [
          "C X",
          2
        ],
        [
          "C Y",
          6
        ],
        [
          "C Z",
          7
        ]
      ]);
  return Js_array.reduce((function (accu, val) {
                return accu + scoring[val] | 0;
              }), 0, input);
}

var rock = 1;

var paper = 2;

var scissor = 3;

var lost = 0;

var draw = 3;

var won = 6;

export {
  rock ,
  paper ,
  scissor ,
  lost ,
  draw ,
  won ,
  part01 ,
  part02 ,
}
/* No side effect */
