// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Os from "os";
import * as Utils from "./Utils.bs.js";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Js_array from "rescript/lib/es6/js_array.js";
import * as Js_string from "rescript/lib/es6/js_string.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function run(param) {
  return Utils.unwrapOrRaise({
              RE_EXN_ID: Utils.WentSouth
            }, Caml_option.undefined_to_opt(Utils.sortNumbers(Js_array.map((function (line) {
                              var partial_arg = {
                                RE_EXN_ID: Utils.WentSouth
                              };
                              return Js_array.reduce((function (prim0, prim1) {
                                            return prim0 + prim1 | 0;
                                          }), 0, Js_array.map((function (param) {
                                                return Utils.unwrapOrRaise(partial_arg, param);
                                              }), Js_array.map(Belt_Int.fromString, Js_string.split(Os.EOL, line))));
                            }), Js_string.split(Os.EOL + Os.EOL, Utils.loadInput(1)))).pop()));
}

export {
  run ,
}
/* os Not a pure module */
